export const FETCH_ALL_IDS_SUCCESS = 'FETCH_ALL_IDS_SUCCESS';
export const FETCH_ALL_IDS_FAIL = 'FETCH_ALL_IDS_FAIL';
export const FETCH_ALL_IDS_START = 'FETCH_ALL_IDS_START';

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';
export const FETCH_NEWS_START = 'FETCH_NEWS_START';